NAME_DB = 'rampy'
USER_DB = 'naruto'
PASSWORD_DB = 'voloda2000'
HOST = 'localhost'
PORT = 5432

EMAIL_HOST_CONFIG = 'smtp.ukr.net'
EMAIL_HOST_USER_CONFIG = 'rampy265@ukr.net'
EMAIL_HOST_PASSWORD_CONFIG = 'GsjrCotdAOcckrpZ'
EMAIL_PORT_CONFIG = 465
EMAIL_USE_TLS_CONFIG = True
EMAIL_USE_SSL_CONFIG = False
